require('nvim-cmp-setup')
require('luasnip-setup')
require('lsp-config-setup')
require('plugins')
require('settings')
require('tree-sitter-setup')
require('vscode-theme-setup')
require('comment-setup')
